# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags:
      - 'v*.*.*'
    branches: [ master ]
  pull_request:
    branches: [ master, feature/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
      export SHORT_COMMIT=${GITHUB_SHA:0:7}
      export LAMBDA_VERSION=$(unzip -p logdna_cloudwatch_lambda.zip package.json | jq -r .version | tr "." "_")
      echo "::set-env name=SHORT_COMMIT::$SHORT_COMMIT"
      echo "::set-env name=LAMBDA_VERSION::$LAMBDA_VERSION"
    - run: npm install
    - run: npm run lint
    - run: npm run build --if-present
    - run: npm run test
    - run: npm install --production
    - run: zip logdna-cloudwatch-$LAMBDA_VERSISON-$SHORT_COMMIT.zip -r node_modules/ index.js package.json
      
    - name: Upload LogDNA Cloudwatch
      uses: actions/upload-artifact@v1
      with:
        name: logdna-cloudwatch-${{ env.LAMBDA_VERSION }}-${{ env.SHORT_COMMIT }}.zip
        path: ./logdna-cloudwatch-${{ env.LAMBDA_VERSION }}-${{ env.SHORT_COMMIT }}.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./logdna-cloudwatch-${{ env.LAMBDA_VERSION }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

